### PR TITLE
Linux support

### PR DESCRIPTION
**Pull request by joaompneves**
Follow-up of #119 
---
This PR adds support for Linux x64 platform. If asked, the Linux ARM64 platform can be added as well.

Includes edits from PR https://github.com/OutSystems/CefGlue/pull/88 alongside with my own edits https://github.com/OutSystems/CefGlue/pull/88#issuecomment-1814829113.

Requires more testing.

Tested on these platforms and hardware configurations:

✔️ Arch Linux with Intel GPU: Works well.
✔️ Arch Linux with NVIDIA GPU (Proprietary Drivers): Works well.
✔️ Arch Linux with NVIDIA GPU (Lately Open-Sourced Drivers): Works well.
❌ Debian 12 on QEMU virtual machine (GPU options: Virtio, VGA, QXL): No window shows up. Error message says libva device = null on some devices. Disabling GPU with "--disable-gpu" did nothing.
Needs testing on:

AMD GPU
Other distributions

### CODE REVIEW

**Comment by Haltroy** [comment]
Great that one job somehow fixed itself but It's no longer working on my end and I have no idea why it started doing this. 

First, It gave an error that it couldn't find `libcef.so` and I can confirm that it not copied to the output folder. So I copied it to the output folder and got another error:
`[1123/202210.006079:ERROR:icu_util.cc(240)] Invalid file descriptor to ICU data received.`

Google'd it, turns out CefSharp users did also had the same issue for a time caused by files not copying properly.

Copied the files and now it is telling me that .NET 6.0 is not installed, `dotnet --list-runtimes` and `dotnet --list-sdks` do include it, tried building another .NET 6.0 app and it worked.

CEF on Linux is cursed and I don't want to work on it anymore. Glad you took the control over because I was just this close to ask you to take it to your own hands.

Good luck, hope you won't need it. This is my last comment.

**Comment by JerryJian** [comment]
@joaompneves any progress on this?

**Comment by joaompneves** [comment]
Nope. I opened this PR to unblock some pipeline issues we were having, but I did not authored the changes. 
Unless anyone interested pursues this, I won't be following-up. I can help but won't lead.

**Comment by Haltroy** [comment]
Started working on this again, it finally copies the subprocess but now I can't load libcef.so from subprocess's path. It's an issue on `Xilium.CefGlue.CefRuntime.CheckVersionByApiHash` function which crashes on `libcef.api_hash(0)` line.
Copying the entire CEF into the application folder fixes it but that wouldn't be ideal since this way you would end with 2 CEF's (both combined is 400MB) in both the application's folder and in `CefGlueBrowserProcess` folder. For now this is at the highest priority on my TODO list.

Also, tested on virtual machine (Fedora 39) and my system (Arch) to discover that it still won't render on normal mode but renders on WindowlessRender mode. Also it randomly crashes. I'm investigating both of these 2 issues to see what's causing them but they are now in lower priority. 

I'll create a PR again once I'm sure that it is done but now everyone can access my fork from [`here`](https://github.com/Haltroy/CefGlue). I also had to publish CEF binaries under another name (yes the only missing thing in my way was me not stripping binaries). It's available [`here`](https://github.com/Haltroy/cef.bin.linux).

**Comment by Haltroy** [comment]
I discovered that it still won't render on normal mode because we simply don't have a wrapper for libX11 and thus CEF gives X errors while attempting to bind to Avalonia control. I simply lack on making wrappers for C#.

In the future when Avalonia finally supports Wayland, we also need a wrapper for that but for now since Avalonia is X11 only we don't have to make that.

**Comment by baimindong** [comment]
Unhandled exception. System.IO.FileNotFoundException: Unable to find SubProcess. Probed locations: /linux-x64/CefGlueBrowserProcess/Xilium.CefGlue.BrowserProcess

**Comment by baimindong** [comment]
Unhandled exception. System.IO.FileNotFoundException: Unable to find SubProcess. Probed locations: /linux-x64/CefGlueBrowserProcess/Xilium.CefGlue.BrowserProcess

**Comment by baimindong** [comment]
Unhandled exception. System.IO.FileNotFoundException: Unable to find SubProcess. Probed locations: /linux-x64/CefGlueBrowserProcess/Xilium.CefGlue.BrowserProcess

**Comment by walterlv** [comment]
@Haltroy I just ran your offscreen rendering and it worked correctly. And now I'll try to implement the Avalonia native control host on X11 based on your branch and this .NET 8 main branch. I hope we can keep in touch to share our knowledge and process.

**Comment by Haltroy** [comment]
> @Haltroy I just ran your offscreen rendering and it worked correctly. And now I'll try to implement the Avalonia native control host on X11 based on your branch and this .NET 8 main branch. I hope we can keep in touch to share our knowledge and process.

My current branch is using the old Avalonia 10.x code and I haven't updated it properly yet. Will do that right after my finals are done. But I'm glad that someone can help with this issue that's haunting me for months.

**Comment by walterlv** [comment]
> My current branch is using the old Avalonia 10.x code and I haven't updated it properly yet. Will do that right after my finals are done. But I'm glad that someone can help with this issue that's haunting me for months.

I've updated it, don't worry.

https://github.com/OutSystems/CefGlue/pull/146

**Comment by Haltroy** [comment]
> > My current branch is using the old Avalonia 10.x code and I haven't updated it properly yet. Will do that right after my finals are done. But I'm glad that someone can help with this issue that's haunting me for months.
> 
> I've updated it, don't worry.
> 
> #146

Updated mine as well, please see the edit I made above.

**Comment by walterlv** [comment]
@Haltroy 

@kkwpsv has a new great job on this. See here: https://github.com/Haltroy/CefGlue/pull/3

**Comment by joaompneves** [comment]
Now available: [120.6099.204](https://www.nuget.org/packages/CefGlue.Avalonia/120.6099.204)

**Pull request closed without merging**
